language: c
sudo: true

before_script:
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get update
  - sudo apt-get -y install neovim
  - git clone https://github.com/junegunn/vader.vim.git

script:
  - make test_ci

notifications:
  email: false
